* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 0
*   Variables        : 0
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 0
NAME          
ROWS
 N  COST
ENDATA
