# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.1.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.1.0")
   message(FATAL_ERROR "CMake >= 3.1.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.1.0...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Antares::solver_api Antares::single_problem_api Antares::antares-problem-generator Antares::study Antares::scenario-builder-utils Antares::study-loader Antares::file-tree-study-loader Antares::antares-solver-simulation Antares::yuni-static-core Antares::array Antares::date Antares::inifile Antares::StudyUtils Antares::utils Antares::correlation Antares::path Antares::mersenne Antares::result_writer Antares::series Antares::antares-core Antares::antares-solver-hydro Antares::exception Antares::benchmarking Antares::antares-solver-variable Antares::lps Antares::application Antares::infoCollection Antares::concurrency Antares::misc Antares::model_antares Antares::antares-solver-ts-generator Antares::shave-peaks-by-remix-storage-gen Antares::storage-for-remix-list-sort Antares::io Antares::jit Antares::AntaresMemory Antares::logs Antares::locator Antares::antares-config-lib Antares::solver-lib Antares::sys Antares::signal-handling Antares::antares-solver-variable-info Antares::optimization-options Antares::resources Antares::infeasible_problem_analysis Antares::linear-problem-api Antares::linear-problem-data-impl Antares::linear-problem-mpsolver-impl Antares::modeler-lib Antares::args_helper Antares::checks Antares::locale Antares::yuni-static-uuid Antares::antares-solver Antares::antlr-interface Antares::antares-study-system-model Antares::load-modeler-files Antares::write-modeler-files Antares::modeler-optimisation-container Antares::expressions Antares::optim-model-filler Antares::yml-system Antares::yml-model Antares::model-converter Antares::modeler-parameters Antares::data-series-csv-importer Antares::expressions-iterators Antares::additional-constraint-rhs-antlr-interface Antares::modeler-simulation-table Antares::scenario-builder-antlr Antares::scenario-group-parser Antares::yml-optim-config Antares::enums Antares::modeler-checks Antares::structured-linear-problem)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Antares::solver_api
add_library(Antares::solver_api STATIC IMPORTED)

set_target_properties(Antares::solver_api PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::file-tree-study-loader>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::study-loader>;\$<LINK_ONLY:Antares::antares-solver-simulation>;\$<LINK_ONLY:Boost::iostreams>;\$<LINK_ONLY:Antares::enums>;Antares::optimization-options;Antares::lps"
)

# Create imported target Antares::single_problem_api
add_library(Antares::single_problem_api STATIC IMPORTED)

set_target_properties(Antares::single_problem_api PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:fmt::fmt>;\$<LINK_ONLY:Antares::antares-solver-simulation>;\$<LINK_ONLY:Antares::optimization-options>;\$<LINK_ONLY:Antares::model_antares>;\$<LINK_ONLY:Antares::antares-solver-hydro>;\$<LINK_ONLY:Antares::file-tree-study-loader>;Antares::study;Antares::lps"
)

# Create imported target Antares::antares-problem-generator
add_executable(Antares::antares-problem-generator IMPORTED)

set_target_properties(Antares::antares-problem-generator PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::study
add_library(Antares::study STATIC IMPORTED)

set_target_properties(Antares::study PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;Antares::date;Antares::inifile;Antares::StudyUtils;Antares::utils;Antares::correlation;Antares::path;Antares::mersenne;Antares::result_writer;Antares::series;Antares::array;Antares::antares-core;Antares::antares-solver-simulation;Antares::antares-solver-hydro;Antares::antares-study-system-model;Antares::linear-problem-api;Antares::load-modeler-files;Antares::modeler-parameters;Antares::modeler-lib;Antares::scenario-builder-utils;Antares::enums;\$<LINK_ONLY:Antares::exception>;\$<LINK_ONLY:fmt::fmt>;\$<LINK_ONLY:Antares::benchmarking>;\$<LINK_ONLY:Antares::antares-solver-variable>;\$<LINK_ONLY:Antares::additional-constraint-rhs-antlr-interface>"
)

# Create imported target Antares::scenario-builder-utils
add_library(Antares::scenario-builder-utils STATIC IMPORTED)

set_target_properties(Antares::scenario-builder-utils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core"
)

# Create imported target Antares::study-loader
add_library(Antares::study-loader INTERFACE IMPORTED)

set_target_properties(Antares::study-loader PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::file-tree-study-loader
add_library(Antares::file-tree-study-loader STATIC IMPORTED)

set_target_properties(Antares::file-tree-study-loader PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::study-loader;Antares::result_writer;Antares::study;Antares::application"
)

# Create imported target Antares::antares-solver-simulation
add_library(Antares::antares-solver-simulation STATIC IMPORTED)

set_target_properties(Antares::antares-solver-simulation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::infoCollection;Antares::yuni-static-core;Antares::study;Antares::result_writer;Antares::concurrency;Antares::utils;Antares::misc;Antares::model_antares;Antares::antares-solver-hydro;Antares::antares-solver-variable;Antares::antares-solver-ts-generator;Antares::shave-peaks-by-remix-storage-gen;Antares::modeler-simulation-table"
)

# Create imported target Antares::yuni-static-core
add_library(Antares::yuni-static-core STATIC IMPORTED)

set_target_properties(Antares::yuni-static-core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::array
add_library(Antares::array STATIC IMPORTED)

set_target_properties(Antares::array PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;Antares::io;Antares::jit;Antares::AntaresMemory;Antares::StudyUtils"
)

# Create imported target Antares::date
add_library(Antares::date STATIC IMPORTED)

set_target_properties(Antares::date PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::study;\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::inifile
add_library(Antares::inifile STATIC IMPORTED)

set_target_properties(Antares::inifile PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;\$<LINK_ONLY:Antares::io>;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Boost::headers>"
)

# Create imported target Antares::StudyUtils
add_library(Antares::StudyUtils STATIC IMPORTED)

set_target_properties(Antares::StudyUtils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::utils
add_library(Antares::utils STATIC IMPORTED)

set_target_properties(Antares::utils PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-Wno-unused-variable"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ortools::ortools;sirius_solver;Antares::study;Antares::result_writer;Antares::optimization-options;Antares::antares-core"
)

# Create imported target Antares::correlation
add_library(Antares::correlation STATIC IMPORTED)

set_target_properties(Antares::correlation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::inifile>;\$<LINK_ONLY:Antares::array>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::locator>"
)

# Create imported target Antares::path
add_library(Antares::path STATIC IMPORTED)

set_target_properties(Antares::path PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::mersenne
add_library(Antares::mersenne STATIC IMPORTED)

set_target_properties(Antares::mersenne PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>"
)

# Create imported target Antares::result_writer
add_library(Antares::result_writer STATIC IMPORTED)

set_target_properties(Antares::result_writer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::benchmarking;Antares::yuni-static-core;\$<LINK_ONLY:MINIZIP::minizip-ng>;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::inifile>;\$<LINK_ONLY:Antares::io>;\$<LINK_ONLY:Antares::concurrency>"
)

# Create imported target Antares::series
add_library(Antares::series STATIC IMPORTED)

set_target_properties(Antares::series PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::array;Antares::antares-core"
)

# Create imported target Antares::antares-core
add_library(Antares::antares-core STATIC IMPORTED)

set_target_properties(Antares::antares-core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;Antares::logs;Antares::exception;Antares::study;Antares::antares-config-lib"
)

# Create imported target Antares::antares-solver-hydro
add_library(Antares::antares-solver-hydro STATIC IMPORTED)

set_target_properties(Antares::antares-solver-hydro PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::model_antares>;\$<LINK_ONLY:Antares::antares-solver-variable>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::mersenne>;sirius_solver;Antares::date;Antares::result_writer"
)

# Create imported target Antares::exception
add_library(Antares::exception STATIC IMPORTED)

set_target_properties(Antares::exception PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::benchmarking
add_library(Antares::benchmarking STATIC IMPORTED)

set_target_properties(Antares::benchmarking PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::inifile>"
)

# Create imported target Antares::antares-solver-variable
add_library(Antares::antares-solver-variable STATIC IMPORTED)

set_target_properties(Antares::antares-solver-variable PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::antares-solver-simulation;\$<LINK_ONLY:Antares::antares-core>;\$<LINK_ONLY:Antares::study>"
)

# Create imported target Antares::lps
add_library(Antares::lps STATIC IMPORTED)

set_target_properties(Antares::lps PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "fmt::fmt;Antares::exception;Antares::linear-problem-api"
)

# Create imported target Antares::application
add_library(Antares::application STATIC IMPORTED)

set_target_properties(Antares::application PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;Antares::study;Antares::infoCollection;Antares::solver-lib;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::sys>;\$<LINK_ONLY:Antares::utils>;\$<LINK_ONLY:Antares::signal-handling>;\$<LINK_ONLY:Antares::resources>;\$<LINK_ONLY:Antares::file-tree-study-loader>;\$<LINK_ONLY:Antares::modeler-simulation-table>"
)

# Create imported target Antares::infoCollection
add_library(Antares::infoCollection STATIC IMPORTED)

set_target_properties(Antares::infoCollection PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;Antares::benchmarking;Antares::study"
)

# Create imported target Antares::concurrency
add_library(Antares::concurrency STATIC IMPORTED)

set_target_properties(Antares::concurrency PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core"
)

# Create imported target Antares::misc
add_library(Antares::misc STATIC IMPORTED)

set_target_properties(Antares::misc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::exception>;\$<LINK_ONLY:Antares::StudyUtils>;Antares::yuni-static-core;Antares::study"
)

# Create imported target Antares::model_antares
add_library(Antares::model_antares STATIC IMPORTED)

set_target_properties(Antares::model_antares PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-Wno-unused-variable"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::utils;sirius_solver;Antares::antares-solver-simulation;Antares::benchmarking;Antares::optimization-options;Antares::lps;\$<LINK_ONLY:Antares::infeasible_problem_analysis>;\$<LINK_ONLY:Antares::linear-problem-api>;\$<LINK_ONLY:Antares::linear-problem-data-impl>;\$<LINK_ONLY:Antares::linear-problem-mpsolver-impl>;\$<LINK_ONLY:Antares::optim-model-filler>;\$<LINK_ONLY:Antares::antares-study-system-model>;\$<LINK_ONLY:Antares::modeler-simulation-table>;\$<LINK_ONLY:Boost::headers>"
)

# Create imported target Antares::antares-solver-ts-generator
add_library(Antares::antares-solver-ts-generator STATIC IMPORTED)

set_target_properties(Antares::antares-solver-ts-generator PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::result_writer>;\$<LINK_ONLY:Antares::array>;\$<LINK_ONLY:Antares::benchmarking>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::misc>;\$<LINK_ONLY:Antares::antares-solver-simulation>;\$<LINK_ONLY:fmt::fmt>"
)

# Create imported target Antares::shave-peaks-by-remix-storage-gen
add_library(Antares::shave-peaks-by-remix-storage-gen STATIC IMPORTED)

set_target_properties(Antares::shave-peaks-by-remix-storage-gen PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::storage-for-remix-list-sort>"
)

# Create imported target Antares::storage-for-remix-list-sort
add_library(Antares::storage-for-remix-list-sort STATIC IMPORTED)

set_target_properties(Antares::storage-for-remix-list-sort PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::io
add_library(Antares::io STATIC IMPORTED)

set_target_properties(Antares::io PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::jit
add_library(Antares::jit STATIC IMPORTED)

set_target_properties(Antares::jit PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;Antares::logs"
)

# Create imported target Antares::AntaresMemory
add_library(Antares::AntaresMemory STATIC IMPORTED)

set_target_properties(Antares::AntaresMemory PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;Antares::logs;\$<LINK_ONLY:Antares::sys>"
)

# Create imported target Antares::logs
add_library(Antares::logs STATIC IMPORTED)

set_target_properties(Antares::logs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core"
)

# Create imported target Antares::locator
add_library(Antares::locator STATIC IMPORTED)

set_target_properties(Antares::locator PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::study;\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::resources>"
)

# Create imported target Antares::antares-config-lib
add_library(Antares::antares-config-lib STATIC IMPORTED)

set_target_properties(Antares::antares-config-lib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::solver-lib
add_library(Antares::solver-lib INTERFACE IMPORTED)

set_target_properties(Antares::solver-lib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::args_helper;Antares::date;Antares::benchmarking;Antares::result_writer;Antares::sys;Antares::infoCollection;Antares::checks;Antares::misc;Antares::optimization-options;Antares::signal-handling;Antares::locale;Antares::yuni-static-uuid;Antares::yuni-static-core;Antares::antares-solver-hydro;Antares::antares-solver-variable;Antares::antares-solver-simulation;Antares::antares-solver-ts-generator;Antares::model_antares;Antares::antares-core"
)

# Create imported target Antares::sys
add_library(Antares::sys STATIC IMPORTED)

set_target_properties(Antares::sys PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;\$<LINK_ONLY:Antares::antares-core>;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::inifile>;\$<LINK_ONLY:Antares::antares-config-lib>"
)

# Create imported target Antares::signal-handling
add_library(Antares::signal-handling STATIC IMPORTED)

set_target_properties(Antares::signal-handling PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::study>;Antares::result_writer;Antares::AntaresMemory"
)

# Create imported target Antares::antares-solver-variable-info
add_library(Antares::antares-solver-variable-info STATIC IMPORTED)

set_target_properties(Antares::antares-solver-variable-info PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::antares-core>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::antares-solver-simulation>"
)

# Create imported target Antares::optimization-options
add_library(Antares::optimization-options STATIC IMPORTED)

set_target_properties(Antares::optimization-options PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::resources
add_library(Antares::resources STATIC IMPORTED)

set_target_properties(Antares::resources PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::antares-config-lib>"
)

# Create imported target Antares::infeasible_problem_analysis
add_library(Antares::infeasible_problem_analysis STATIC IMPORTED)

set_target_properties(Antares::infeasible_problem_analysis PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ortools::ortools>;\$<LINK_ONLY:Boost::headers>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::linear-problem-api
add_library(Antares::linear-problem-api STATIC IMPORTED)

set_target_properties(Antares::linear-problem-api PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::linear-problem-data-impl
add_library(Antares::linear-problem-data-impl STATIC IMPORTED)

set_target_properties(Antares::linear-problem-data-impl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::linear-problem-api;fmt::fmt;Antares::exception"
)

# Create imported target Antares::linear-problem-mpsolver-impl
add_library(Antares::linear-problem-mpsolver-impl STATIC IMPORTED)

set_target_properties(Antares::linear-problem-mpsolver-impl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::linear-problem-api;Antares::logs;Antares::utils;ortools::ortools"
)

# Create imported target Antares::modeler-lib
add_library(Antares::modeler-lib STATIC IMPORTED)

set_target_properties(Antares::modeler-lib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::modeler-parameters;Antares::optim-model-filler;Antares::linear-problem-api;Antares::structured-linear-problem;Antares::linear-problem-mpsolver-impl"
)

# Create imported target Antares::args_helper
add_library(Antares::args_helper STATIC IMPORTED)

set_target_properties(Antares::args_helper PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>"
)

# Create imported target Antares::checks
add_library(Antares::checks STATIC IMPORTED)

set_target_properties(Antares::checks PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::exception;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::exception>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::antares-core>;\$<LINK_ONLY:Antares::enums>"
)

# Create imported target Antares::locale
add_library(Antares::locale STATIC IMPORTED)

set_target_properties(Antares::locale PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>"
)

# Create imported target Antares::yuni-static-uuid
add_library(Antares::yuni-static-uuid STATIC IMPORTED)

set_target_properties(Antares::yuni-static-uuid PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "uuid"
)

# Create imported target Antares::antares-solver
add_executable(Antares::antares-solver IMPORTED)

set_target_properties(Antares::antares-solver PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::antlr-interface
add_library(Antares::antlr-interface STATIC IMPORTED)

set_target_properties(Antares::antlr-interface PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "antlr4_static"
)

# Create imported target Antares::antares-study-system-model
add_library(Antares::antares-study-system-model STATIC IMPORTED)

set_target_properties(Antares::antares-study-system-model PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::expressions;\$<LINK_ONLY:Antares::exception>"
)

# Create imported target Antares::load-modeler-files
add_library(Antares::load-modeler-files STATIC IMPORTED)

set_target_properties(Antares::load-modeler-files PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::antares-study-system-model;Antares::linear-problem-api;Antares::linear-problem-data-impl;\$<LINK_ONLY:Antares::io>;\$<LINK_ONLY:Antares::yml-optim-config>;\$<LINK_ONLY:Antares::yml-system>;\$<LINK_ONLY:Antares::yml-model>;\$<LINK_ONLY:Antares::model-converter>;\$<LINK_ONLY:Antares::modeler-parameters>;\$<LINK_ONLY:Antares::data-series-csv-importer>;\$<LINK_ONLY:Antares::modeler-lib>;\$<LINK_ONLY:Antares::scenario-group-parser>;\$<LINK_ONLY:Antares::StudyUtils>;\$<LINK_ONLY:Antares::modeler-checks>;\$<LINK_ONLY:fmt::fmt>"
)

# Create imported target Antares::write-modeler-files
add_library(Antares::write-modeler-files STATIC IMPORTED)

set_target_properties(Antares::write-modeler-files PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::antares-study-system-model;Antares::linear-problem-api;Antares::linear-problem-data-impl;\$<LINK_ONLY:Antares::io>;\$<LINK_ONLY:Antares::modeler-lib>"
)

# Create imported target Antares::modeler-optimisation-container
add_library(Antares::modeler-optimisation-container STATIC IMPORTED)

set_target_properties(Antares::modeler-optimisation-container PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::antares-study-system-model>;\$<LINK_ONLY:Antares::linear-problem-api>"
)

# Create imported target Antares::expressions
add_library(Antares::expressions STATIC IMPORTED)

set_target_properties(Antares::expressions PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Boost::headers;Antares::antares-study-system-model;Antares::logs;fmt::fmt;Antares::linear-problem-api;Antares::optim-model-filler;Antares::modeler-optimisation-container;Antares::optim-model-filler;\$<LINK_ONLY:Antares::exception>"
)

# Create imported target Antares::optim-model-filler
add_library(Antares::optim-model-filler STATIC IMPORTED)

set_target_properties(Antares::optim-model-filler PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::modeler-optimisation-container>;\$<LINK_ONLY:Antares::expressions>;\$<LINK_ONLY:Antares::exception>;\$<LINK_ONLY:Antares::antares-study-system-model>;\$<LINK_ONLY:Antares::linear-problem-api>;\$<LINK_ONLY:fmt::fmt>"
)

# Create imported target Antares::yml-system
add_library(Antares::yml-system STATIC IMPORTED)

set_target_properties(Antares::yml-system PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::antares-study-system-model;\$<LINK_ONLY:yaml-cpp::yaml-cpp>"
)

# Create imported target Antares::yml-model
add_library(Antares::yml-model STATIC IMPORTED)

set_target_properties(Antares::yml-model PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:yaml-cpp::yaml-cpp>"
)

# Create imported target Antares::model-converter
add_library(Antares::model-converter STATIC IMPORTED)

set_target_properties(Antares::model-converter PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::antares-study-system-model>;\$<LINK_ONLY:Antares::yml-model>;\$<LINK_ONLY:Antares::antlr-interface>;\$<LINK_ONLY:Antares::expressions>;\$<LINK_ONLY:Antares::expressions-iterators>"
)

# Create imported target Antares::modeler-parameters
add_library(Antares::modeler-parameters STATIC IMPORTED)

set_target_properties(Antares::modeler-parameters PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:yaml-cpp::yaml-cpp>;\$<LINK_ONLY:Antares::io>"
)

# Create imported target Antares::data-series-csv-importer
add_library(Antares::data-series-csv-importer STATIC IMPORTED)

set_target_properties(Antares::data-series-csv-importer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::linear-problem-data-impl;\$<LINK_ONLY:Boost::headers>;\$<LINK_ONLY:Boost::iostreams>"
)

# Create imported target Antares::expressions-iterators
add_library(Antares::expressions-iterators STATIC IMPORTED)

set_target_properties(Antares::expressions-iterators PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::expressions>"
)

# Create imported target Antares::additional-constraint-rhs-antlr-interface
add_library(Antares::additional-constraint-rhs-antlr-interface STATIC IMPORTED)

set_target_properties(Antares::additional-constraint-rhs-antlr-interface PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "antlr4_static"
)

# Create imported target Antares::modeler-simulation-table
add_library(Antares::modeler-simulation-table STATIC IMPORTED)

set_target_properties(Antares::modeler-simulation-table PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::linear-problem-data-impl;Antares::optim-model-filler;Antares::antares-study-system-model;Antares::modeler-lib;Antares::StudyUtils;\$<LINK_ONLY:Antares::modeler-lib>"
)

# Create imported target Antares::scenario-builder-antlr
add_library(Antares::scenario-builder-antlr STATIC IMPORTED)

set_target_properties(Antares::scenario-builder-antlr PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "antlr4_static"
)

# Create imported target Antares::scenario-group-parser
add_library(Antares::scenario-group-parser STATIC IMPORTED)

set_target_properties(Antares::scenario-group-parser PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::scenario-builder-antlr;\$<LINK_ONLY:fmt::fmt>;\$<LINK_ONLY:Antares::exception>"
)

# Create imported target Antares::yml-optim-config
add_library(Antares::yml-optim-config STATIC IMPORTED)

set_target_properties(Antares::yml-optim-config PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:yaml-cpp::yaml-cpp>;\$<LINK_ONLY:Antares::exception>;Antares::antares-study-system-model"
)

# Create imported target Antares::enums
add_library(Antares::enums STATIC IMPORTED)

set_target_properties(Antares::enums PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::exception"
)

# Create imported target Antares::modeler-checks
add_library(Antares::modeler-checks STATIC IMPORTED)

set_target_properties(Antares::modeler-checks PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::antares-study-system-model;\$<LINK_ONLY:Antares::modeler-lib>;\$<LINK_ONLY:fmt::fmt>"
)

# Create imported target Antares::structured-linear-problem
add_library(Antares::structured-linear-problem STATIC IMPORTED)

set_target_properties(Antares::structured-linear-problem PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::linear-problem-api"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/AntaresTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
